### ISSUE TITLE
Switching tabs causes a full page refresh

### ISSUE THREAD

**Issue by MB116** [eminiarts/nova-tabs#146] opened 2021-03-12 04:09 UTC
I apologize for the duplicate question, but the problem is urgent and, unfortunately, so far without a solution. 

I seem to have found the reason for reloading the page when switching tabs.

When we go to editing the resource, the URL by silence "/articles/116/edit", after clicking on the tab, the URL is converted to "/articles/116/edit?tab=material", which causes the page to be updated.

Is there any way to fix this behavior?

**Comment by RVxLab** [comment] 2021-03-12 05:12
When you click on a tab after handling the switching the URI is updated to remember the current tab. The only thing I did to make that happen is simply updating the query string. 

See [this file](https://github.com/eminiarts/nova-tabs/blob/master/resources/js/util/tab-updater.js) for the bit that deals with that.

The only thing I can think of that could remotely cause this is Nova picking up the replacement of the query object as a reload, since Vue is reactive. 

Other than that I have no idea. 

Feel free to propose a fix in a PR.

**Comment by SquareBeard** [comment] 2021-05-14 13:12
I have noticed the same problem when editing resources.
You must first click on another tab before filling the first one, or all the data will be lost when switching tabs because of the reload.
Is there a way to disable this behaviour ? I don't think I care about saving the active tab in the url. But I do care about loss of data.

**Comment by RVxLab** [comment] 2021-05-14 13:17
There is currently no way to disable this, but since this is causing some major issues with reload I think it's better to sunset the updating URL entirely and move it to local or session storage.

I'll try to take a look this weekend.

**Comment by SquareBeard** [comment] 2021-05-14 13:27
A quick and dirty fix would be to set the `tab` parameter if it is missing immediately after the page load. I will try to do that for now.
A nicer way would be to have the `tab` parameter in the url of the edit link but I'm not sure you can change that.
Or as you said, store it somewhere else.

**Comment by RVxLab** [comment] 2021-05-14 13:30
There is very little I can do to impact this as it's part of Nova's core. Moving it to storage seems like the best option at this time.

Try that workaround for the time being.

**Comment by RVxLab** [comment] 2021-05-16 14:00
I attempted to have a look at this but couldn't find the time to properly do so.

If you want to have a go at it then feel free to submit a PR.

**Comment by SquareBeard** [comment] 2021-05-18 10:52
Meanwhile here is my dirty fix:
```javascript
Nova.request().interceptors.response.use(function (response) {
    if (Array.isArray(response.data.panels) && Array.isArray(response.data.fields)) {
        for (let i = 0; i < response.data.panels.length; i++) {
            if (response.data.panels[i].component === 'detail-tabs') {
                const urlParams = new URLSearchParams(window.location.search);
                if (!urlParams.has('tab') && Array.isArray(response.data.fields[0].fields)) {
                    window.location.href = window.location.href + (window.location.href.indexOf('?') === -1 ? '?' : '&') + 'tab=' + response.data.fields[0].fields[0].tabSlug;
                }

                break;
            }
        }
    }

    return response;
});
```

**Comment by BinaryKitten** [comment] 2021-08-11 07:11
> Meanwhile here is my dirty fix:

@SquareBeard where does this "fix" go?

**Comment by SquareBeard** [comment] 2021-08-11 08:58
In a javascript file that you include with `Nova::script(...)` in your NovaServiceProvider.

**Comment by RVxLab** [comment] 2022-02-13 01:30
I'm going to assume that this is fixed due to inactivity. If this issue occurs again please open a new issue.

**Closed by RVxLab** 2022-02-13 01:30 UTC

**Comment by Saifallak** [comment] 2022-02-13 18:36
@RVxLab still not fixed, and happening on latest version

**Comment by Saifallak** [comment] 2022-02-13 19:13
Solution by @SquareBeard https://github.com/eminiarts/nova-tabs/issues/146#issuecomment-843068387
nope, not working well, sometimes work and sometimes not.

**Comment by RVxLab** [comment] 2022-02-13 21:10
> Solution by @SquareBeard [#146 (comment)](https://github.com/eminiarts/nova-tabs/issues/146#issuecomment-843068387)
> nope, not working well, sometimes work and sometimes not.

Not sure what it could be. If someone can find a reliable way to reproduce this then I could have a deeper look. Otherwise I’d gladly accept a PR.

**Comment by RVxLab** [comment] 2022-05-31 20:55
> @RVxLab Could you please open this issue again?
> 
> As I tried following these version and it doesn't work Package Version: v1.5.1 Nova Release: v3.32.0

I don't maintain this package anymore. If this is still an issue in Nova 4 please open a new issue and make a reference to this one, the new maintainers will take it from there.
