### ISSUE TITLE
"Trying to get property 'panel' of non-object" error when upgrade to nova 2.0.8

### ISSUE THREAD

**Issue by bolechen** [eminiarts/nova-tabs#43] opened 2019-07-03 02:27 UTC
When i upgrade to nova 2.0.8, in the edit view have this error:

```
{
    "message": "Trying to get property 'panel' of non-object",
    "exception": "ErrorException",
    "file": "/dev.nova.com/vendor/laravel/nova/src/ResolvesFields.php",
    "line": 518,
    "trace": [
//...
```

**Comment by bolechen** [comment] 2019-07-03 02:29
May be this issue is relate https://github.com/laravel/nova-issues/issues/29

**Comment by bolechen** [comment] 2019-07-04 00:05
related issue https://github.com/laravel/nova-issues/issues/1719

**Comment by WebZenitude** [comment] 2019-07-08 08:27
After Nova 2.0.9:
 - tabs with a single panels and some relations work
 - tabs with two panels and some relations => Error "Trying to get property 'Panel' of non-object".

**Comment by MarceauKa** [comment] 2019-07-08 14:06
Why this issue is closed?

**Comment by WebZenitude** [comment] 2019-07-08 15:59
No idea! :-)

**Comment by kgp43** [comment] 2019-07-09 10:53
Same problem

**Comment by WebZenitude** [comment] 2019-07-09 20:24
There's an help proposal from @davidhemphill here https://github.com/laravel/nova-issues/issues/1719 
Could you have a look @bajramemini ?

**Comment by phuclh** [comment] 2019-07-10 03:20
I have the same problem with nova 2.0.9

**Comment by kgp43** [comment] 2019-07-10 05:00
I ended up disable the package.
Would be nice, if Nova will add tabs.

**Comment by iamoat** [comment] 2019-07-11 07:51
Even though I have downgraded nova to 2.0.6, the edit page with Tabs has nothing shown at all. :'-(

**Comment by bolechen** [comment] 2019-07-11 07:56
> Even though I have downgraded nova to 2.0.6, the edit page with Tabs has nothing shown at all. :'-(

when downgraded u need run nova:publish again

**Comment by phuclh** [comment] 2019-07-13 21:18
any solution for this problem :(

**Comment by WebZenitude** [comment] 2019-07-14 04:02
No commit since April 2019 @bajramemini , can I ask you what are your intents with this nova-tabs?
You did such a great work until now, it would be a pity to give it up.
A solution could be to let @davidhemphill include these tabs directly in Nova and then maintain the compatibility with the next Nova versions.

**Comment by 949mac** [comment] 2019-07-18 22:18
❗Same problem here.

I've downgraded to Nova 2.0.6 as well, and then ran:

```
php artisan nova:publish
php artisan view:clear
```

**Comment by audetcameron** [comment] 2019-07-19 15:49
turn off use TabsOnEdit   for now.
you can still see tabs on detail pages.

**Comment by rikless** [comment] 2019-07-22 07:24
Same problem here. Any plan to update @bajramemini ?

**Comment by bajramemini** [comment] 2019-07-23 20:23
Hello everyone

Sorry for the long delay, have been on vacation for a couple of weeks and didn't receive any notification about this issue.

Will try to solve it asap and keep you updated.

**Comment by ArmeniaH** [comment] 2019-07-23 20:46
Thank you very much :))

**Comment by bajramemini** [comment] 2019-07-24 15:28
Should work as of [1.0.5](https://github.com/eminiarts/nova-tabs/releases/tag/1.0.5)

- Should not break anything (hopefully)
- Had to modify the `assignToPanels()` function. If it is used somewhere else and breaks anything, please let me know.

Kind regards
Bajram

**Comment by phuclh** [comment] 2019-07-24 22:25
@bajramemini After updated to 1.0.5 it doesn't show that error anymore, but there is no filed display. Only the buttons are displayed.

<img width="1474" alt="Screen Shot 2019-07-24 at 3 24 36 PM" src="https://user-images.githubusercontent.com/6707194/61832802-2e953a00-ae27-11e9-9522-06ca15d37971.png">

**Comment by onemoreahmad** [comment] 2019-07-24 22:35
Same here, fields disappeared on 1.0.5 and Nova 2.0.9.

**Comment by onemoreahmad** [comment] 2019-07-24 22:46
Ignore my previous comment, actually it works! the issue was from something else.

**Comment by ArmeniaH** [comment] 2019-07-24 23:20
I can confirm that Edit View has empty view with only buttons, as @phuclh mentioned

**Comment by bolechen** [comment] 2019-07-24 23:59
> Should work as of [1.0.5](https://github.com/eminiarts/nova-tabs/releases/tag/1.0.5)
> 
> * Should not break anything (hopefully)
> * Had to modify the `assignToPanels()` function. If it is used somewhere else and breaks anything, please let me know.
> 
> Kind regards
> Bajram
looks this fixed for me. thx for your work.

@onemoreahmad @phuclh your need run `nova:publish` after each upgrade.

**Comment by phuclh** [comment] 2019-07-25 05:47
@bolechen yeah, I did but it still doesn't show up the fields.

**Comment by iamoat** [comment] 2019-07-25 14:30
Still have a problem when clicking "View" button from an index page. 

Need to down grade Nova to 2.0.6 and Tabs 1.0.4 to get it back to work.

**Comment by rikless** [comment] 2019-07-25 16:52
it's ok for me, thank you @bajramemini !

**Comment by bajramemini** [comment] 2019-07-26 12:37
@phuclh or @iamoat 

What Error do you get?

Could you show me your `Fields` ? So I could try to resolve the issue if there is one. If you upgrade and run `nova:publish` seems to work for most.

**Comment by phuclh** [comment] 2019-07-27 01:19
@bajramemini I did run that command but when I use the `TabsOnEdit` trait. The create view doesn't show any fields, the update view is work, the detail view shows this error.

```
vendor.js?id=eaffe66c3a2800ae7df2:1 TypeError: Cannot set property 'fields' of undefined
    at app.js?id=af7f60e144c36d0eb627:1
    at Function.zo.tap (vendor.js?id=eaffe66c3a2800ae7df2:1)
    at p.createPanelForField (app.js?id=af7f60e144c36d0eb627:1)
    at app.js?id=af7f60e144c36d0eb627:1
    at Array.forEach (<anonymous>)
    at p.availablePanels (app.js?id=af7f60e144c36d0eb627:1)
    at ln.get (vendor.js?id=eaffe66c3a2800ae7df2:1)
    at ln.evaluate (vendor.js?id=eaffe66c3a2800ae7df2:1)
    at p.availablePanels (vendor.js?id=eaffe66c3a2800ae7df2:1)
    at p.render (app.js?id=af7f60e144c36d0eb627:1)
```
I try to remove the trait, everything is good.

**Comment by orlyapps** [comment] 2019-07-27 06:57
I got the same problem. I’ll try to debug this issue.

**Comment by bajramemini** [comment] 2019-07-27 10:59
@phuclh 

Could you show me your `Fields` array? So I could try to debug it.

**Comment by phuclh** [comment] 2019-07-27 21:39
@bajramemini I think it just a normal array. I tried to remove all of the fields and just keep the ID field but the error still shows up.

```
new Tabs('Tabs', [
                'General'     => [
                    Text::make('Title')
                        ->sortable()
                        ->rules('required', 'max:255'),

                    Url::make('URL')
                        ->alwaysClickable()
                        ->sortable()
                        ->rules('required', 'max:255', 'url'),

                    Text::make('Topic')
                        ->sortable()
                        ->rules('required', 'max:255'),

                    Select::make('Type')
                        ->options(self::$model::$types)
                        ->displayUsingLabels()
                        ->rules('required', 'in:' . implode(',', array_keys(self::$model::$types))),

                    BelongsTo::make('Manager', 'manager', User::class)
                ],
                'Credentials' => [
                    Text::make('Identifier')
                        ->rules('max:255')
                        ->hideFromIndex(),

                    TextCopy::make('Password')
                        ->mask()
                        ->rules('max:255')
                        ->hideFromIndex()
                ],
                'Misc'        => [
                    Number::make('Post Frequency')
                        ->rules('nullable', 'numeric')
                        ->hideFromIndex(),

                    Toggle::make('Is Recovered')
                ],
            ]),
```

**Comment by iamoat** [comment] 2019-07-29 10:27
> @phuclh or @iamoat
> 
> What Error do you get?
> 
> Could you show me your `Fields` ? So I could try to resolve the issue if there is one. If you upgrade and run `nova:publish` seems to work for most.

I did run 'php artisan nova:publish' but it didnt' work. 

To reproduce the error. 
1. Enable 'TabsOnEdit' trait
2. Go to index view of the resource. 
3. Click on the 'Detail View' icon.
4. And there the error hit me. 

Note that the 'Edit/Update View' was totally fine. 

The following is my array of fields. 

`
return [
            ID::make()->sortable(),
            Text::make('Name')->sortable(),

            (new Tabs('Tabs', [
                'Licenses' => [
                    Number::make('No. of Extensions', 'limit_extensions'),
                    Number::make('No. of Queues', 'limit_queues'),
                    Number::make('No. of IVR Menus', 'limit_ivrs'),
                ],
                'Local' => [
                    Text::make('Local Call', 'local_call_dial_pattern')->hideFromIndex(),
                    BelongsTo::make('Local Trunk 01', 'local_trunk_01', 'App\Nova\SipTrunk')->hideFromIndex(),
                    Text::make('Local Prepend 01')->hideFromIndex(),
                    Number::make('Local Strip Digits 01')->hideFromIndex(),
                ],
                'Mobile' => [
                    Text::make('Mobile Call', 'mobile_call_dial_pattern')->hideFromIndex(),
                    BelongsTo::make('Mobile Trunk 01', 'mobile_trunk_01', 'App\Nova\SipTrunk')->hideFromIndex(),
                    Text::make('Mobile Prepend 01')->hideFromIndex(),
                    Number::make('Mobile Strip Digits 01')->hideFromIndex(),
                ],
                'Long Distance' => [
                    Text::make('Long Distance Call', 'long_distance_call_dial_pattern')->hideFromIndex(),
                    BelongsTo::make('Long Distance Trunk 01', 'long_distance_trunk_01', 'App\Nova\SipTrunk')->hideFromIndex(),
                    Text::make('Long Distance Prepend 01')->hideFromIndex(),
                    Number::make('Long Distance Strip Digits 01')->hideFromIndex(),
                ],
                'Four Digits' => [
                    Text::make('Four Digits Call', 'four_digits_call_dial_pattern')->hideFromIndex(),
                    BelongsTo::make('Four Digits Trunk 01', 'four_digits_trunk_01', 'App\Nova\SipTrunk')->hideFromIndex(),
                    Text::make('Four Digits Prepend 01')->hideFromIndex(),
                    Number::make('Four Digits Strip Digits 01')->hideFromIndex(),
                ],
                'International' => [
                    Text::make('International Call', 'international_call_dial_pattern')->hideFromIndex(),
                    BelongsTo::make('International Trunk 01', 'international_trunk_01', 'App\Nova\SipTrunk')->hideFromIndex(),
                    Text::make('International Prepend 01')->hideFromIndex(),
                    Number::make('International Strip Digits 01')->hideFromIndex(),
                ]

            ]))->defaultSearch(true),
];
`

![image](https://user-images.githubusercontent.com/1286835/62041391-ba430800-b225-11e9-9913-99e74bc6cc45.png)

**Comment by phuclh** [comment] 2019-07-29 16:57
@iamoat yes, I got that error too.

**Comment by iamoat** [comment] 2019-07-30 03:28
@bolechen Can you re-open the issue since it has not been fixed for my case and @phuclh's yet.

**Comment by bolechen** [comment] 2019-07-30 03:31
@phuclh @iamoat 

It's ok for me now.
Can you test with a fresh install nova to reproduce this issue?

**Comment by WebZenitude** [comment] 2019-07-30 03:38
@phuclh  @iamoat @bajramemini @bolechen 
I still have the issue too.
On a ressource, with `/* use TabsOnEdit; */` the page appears without the TabsOnEdit feature of course.
With `use TabsOnEdit`, the page runs forever (infinite loop somewhere?) and doesn't appear at all.

**Comment by audetcameron** [comment] 2019-07-30 13:33
I have the same issue above,

I don't know if it helps but when I try to 
```
 Log::debug(print_r($request, true));
```
in detailFields() vendor/eminiarts/nova-tabs/src/ActionsInTabs.php
I get  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 2145390592 bytes) {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 4294967296 bytes exhausted (tried to allocate 2145390592 bytes) at /vendor/eminiarts/nova-tabs/src/ActionsInTabs.php:16)

![image](https://user-images.githubusercontent.com/6738453/62133577-ff5e4d00-b2ac-11e9-9e23-1d90cb5b9539.png)

**Comment by rikless** [comment] 2019-07-30 14:13
@iamoat @phuclh run nova:publish is not enough. You may have to disable cache in your dev tools, if you're running `npm run dev/watch`

**Comment by ArmeniaH** [comment] 2019-07-31 06:25
I have empty field only in case of "create" now. "update" and "view" work as expected. no errors in console. checked the api call, its exactly same for "update" and "create", seems issue is coming from JS part

**Comment by ArmeniaH** [comment] 2019-07-31 06:38
@bajramemini 
When I add "panel" also for the creationFields function in TabsOnEdit trait, seems like everything starts working. In your commit, you added only for updateFields function.

<img width="1063" alt="Screen Shot 2019-07-30 at 11 36 13 PM" src="https://user-images.githubusercontent.com/4003433/62189144-1dff2b00-b323-11e9-9443-1e36eb498f58.png">


```
public function creationFields(NovaRequest $request)
    {
        return collect(
            [
                'Tabs' => [
                    'component' => 'tabs',
                    'fields'    => $this->removeNonCreationFields($this->resolveFields($request)),
                    'panel'     => Panel::defaultNameForCreate($request->newResource()),
                ],
            ]
        );
    }
```

**Comment by ArmeniaH** [comment] 2019-08-01 20:51
@bajramemini 
Can you please update the package and release a version with the fix I provided above?
Also it seems there is other case too, and the solution is posted here 
https://github.com/eminiarts/nova-tabs/issues/45

Seems like alot of people is using this package! :)

**Comment by phlisg** [comment] 2019-08-02 06:23
Confirmed everything works by adding @ArmeniaH 's above solution ([two comments above](https://github.com/eminiarts/nova-tabs/issues/43#issuecomment-516718465))

**Comment by iamoat** [comment] 2019-08-04 04:19
> @bajramemini
> Can you please update the package and release a version with the fix I provided above?
> Also it seems there is other case too, and the solution is posted here
> #45
> 
> Seems like alot of people is using this package! :)

This #45 fixed it for me. Now tabs shown correctly both on Edit and Detail views. 

Can somebody make this fix official? @bajramemini

**Comment by funkdoobiest** [comment] 2019-08-07 19:58
Made a PR to fix the issue with missing fields on "create": https://github.com/eminiarts/nova-tabs/pull/46

**Comment by bajramemini** [comment] 2019-08-12 12:20
Hey everyone. 

Sorry, was pretty occupied with work the last days. Thanks for your suggestion.

I merged in the pull request and will release a new version soon.

Doesn't seem to work on one of my projects but will keep you updated.

**Comment by bajramemini** [comment] 2019-08-12 12:49
Lets hope it works with [1.0.6](https://github.com/eminiarts/nova-tabs/releases/tag/1.0.6) 

Let me know if there is still any problem.

**Closed by bajramemini** 2019-08-12 12:49 UTC
Labels: bug
