### ISSUE TITLE
Chinese Tab name is not supported 

### ISSUE THREAD

**Issue by xinxinland** [eminiarts/nova-tabs#167] opened 2021-11-22 09:30 UTC
Does anyone  have this problem ? Tabs name , Chinese is not supported

**Comment by xinxinland** [comment] 2021-11-22 09:37
Chinese Tab name add number ， ok   now

**Comment by RVxLab** [comment] 2021-11-23 06:20
Duplicate of #145. Use the name method on a tab to work around this. 

If you know how to properly fix this I’d gladly accept a PR.

**Closed by RVxLab** 2021-11-23 06:20 UTC
