### ISSUE TITLE
Tab Cannot Handle Chinese Character as Title

### ISSUE THREAD

**Issue by edisonchow88** [eminiarts/nova-tabs#145] opened 2021-02-25 08:17 UTC
Suggestion, update the class Tab with following methods:
 
> class Tab implements TabContract, \JsonSerializable, Arrayable
{
    public function getSlug(): string
    {
        return $this->to_slug($this->getName());
    }
    public function to_slug($string, $separator = '-') {
        $re = "/(\\s|\\".$separator.")+/mu";
        $str = @trim($string);
        $subst = $separator;
        $result = preg_replace($re, $subst, $str);
        return $result;
    }
}

**Comment by RVxLab** [comment] 2021-02-25 11:13
This is not a solution I'll be taking, I'm against suppressing errors.

Please provide a stack trace with an example to reproduce this.

**Comment by RVxLab** [comment] 2021-02-25 11:31
This likely has to do with the fact that `trim()` is **not** multibyte-safe. This should be fixable by only using a regex and only strip whitespace characters from the start and end.

**Comment by RVxLab** [comment] 2021-02-28 12:44
I had a look and wrote a test with Chinese (traditional and simplified), Japanese and Korean. Unexpectedly, these tests pass and make the slug an empty string. See [this commit](https://github.com/eminiarts/nova-tabs/commit/fee5dc6aabc5db25a22218cc5f26c1b166b4397a).

As I don't speak any Asian language at all I'm gonna need you to do (at least) one of the following:

- Provide a code example which causes this error to occur
- Use the `name` property with an ascii string or anything that won't cause issues
- Provide a pull request that fixes the issue that matches the code style used and does **not** use error suppression 
- File a bug report with Laravel as `Tab::getSlug` uses `Str::slug`

If providing a code example, please mention your PHP, Nova, Laravel and Nova Tabs version (I'm assuming the latest at time of writing (1.4.1) if not mentioned).

**Comment by imnpc** [comment] 2021-03-01 09:00
Tabs has something wrong ，tab > 1
1. work ok,URL/ID?tab=contact
```php
            Tabs::make('Relations', [
                HasMany::make('Contact'),
                HasMany::make('Project'),
                HasMany::make('Server'),
                HasMany::make('Account'),
                HasMany::make('Domain'),
               ]),
```
2. work wrong,because URL/ID?tab=???  is empty
```php
            Tabs::make('Relations', [
                HasMany::make('联系人','contact','App\Nova\Contact'),
                HasMany::make('项目','project','App\Nova\Project'),
                HasMany::make('服务器','server','App\Nova\Server'),
                HasMany::make('帐号','account','App\Nova\Account'),
                HasMany::make('域名','domain','App\Nova\Domain'),
               ]),
```
3.work ok,but all tab title font-size is strong
```php
            Tabs::make('Relations', [
                Tab::make('联系人', [
                    HasMany::make('Contact')
                ])->name('Contact'),
                Tab::make('项目', [
                    HasMany::make('Project')
                ])->name('Project'),
                Tab::make('服务器', [
                    HasMany::make('Server')
                ])->name('Server'),
                Tab::make('帐号', [
                    HasMany::make('Account')
                ])->name('Account'),
                Tab::make('域名', [
                    HasMany::make('Domain')
                ])->name('Domain'),
            ]),
```

**Comment by RVxLab** [comment] 2021-03-01 11:41
@imnpc The 2nd example you gave won't work because `Str::slug` returns the title as an empty string (see my previous message). This isn't something neccessarily wrong with the package, this is simply because of how that method works.

If you know of an alternative that can deal with non-ascii characters to resolve this I'm all for it. Until then the best way to fix this is to wrap everything into a Tab object and set the name.

**Comment by RVxLab** [comment] 2022-02-13 01:29
I'm closing this. The way to fix this is by using the `slug` method. If someone can find a better way to fix this I'll gladly accept a PR for it.

**Closed by RVxLab** 2022-02-13 01:29 UTC
