### ISSUE TITLE
Remember current tab

### ISSUE THREAD

**Issue by atmediauk** [eminiarts/nova-tabs#42] opened 2019-06-27 11:07 UTC
Hello,

Is it possible to remember the current tab when editing a resource. When clicking "Update & Continue Editing" it always goes back to the first tab which would be frustrating for users.

**Comment by bolechen** [comment] 2019-07-03 02:25
+1

**Comment by LorenzoSapora** [comment] 2019-09-04 16:06
This is a duplicate of #27

Close and merge into that issue?

**Comment by bernhardh** [comment] 2020-01-09 16:55
With my pull request https://github.com/eminiarts/nova-tabs/pull/86 this should be fixed

**Comment by RVxLab** [comment] 2020-10-19 10:19
This is a duplicate of #27 and PR #86 should fix this. Any additional comments should be put in those.

**Closed by RVxLab** 2020-10-19 10:19 UTC
Labels: enhancement
