### ISSUE TITLE
?tab=Profile takes me to this tab on Detail view but not on Edit view

### ISSUE THREAD

**Issue by keironwaites** [eminiarts/nova-tabs#113] opened 2020-10-17 20:01 UTC
I have discovered that if I add ?tab=Profile to the URL tabs will jump to the Profile tab in detail view - great!

However I would like to deep link to the edit view. When I add ?tab=Profile to the URL here the system does not load the Profile tab.

**Comment by RVxLab** [comment] 2020-10-19 10:42
Doesn't sound like a tough thing to do. I'll try to take a look over the week.

**Comment by keironwaites** [comment] 2020-11-02 06:55
Hey, anything I can do to help with this one?

**Comment by RVxLab** [comment] 2020-11-03 14:37
With all the current open issues regarding the tabs I'm planning something a bit more "dramatic" so to say. Leave it with me for now.

**Comment by keironwaites** [comment] 2020-11-03 16:14
Hi @RVxLab, could you please email me? keiron@gmail.com Thank you.

**Comment by RVxLab** [comment] 2020-11-03 19:23
By the looks of it this has been fixed with #86 

It *should've* been released with 1.3.0, but that wasn't tagged yet. Keep an eye on this.

As for your email, why do you need this?

**Comment by keironwaites** [comment] 2020-11-03 19:47
I would like to discuss possible remuneration. Thanks.

**Comment by RVxLab** [comment] 2020-11-03 20:07
This sounds like something you'd need to discuss with @bajramemini. I don't own this repo, I merely help maintain it.

**Comment by muddymatches** [comment] 2020-11-10 06:31
This is fixed as far as I can tell in 1.3.0.

**Comment by RVxLab** [comment] 2020-11-15 10:20
I'll close this issue for now under the assumption it's fixed. If the issue is still there then please reopen.

**Closed by RVxLab** 2020-11-15 10:20 UTC
Labels: enhancement
