### ISSUE TITLE
HasTabs trait hides relationship panels in Laravel Nova 4.10.1

### ISSUE THREAD

**Issue by mikkellindblom** [eminiarts/nova-tabs#229] opened 2022-06-28 11:58 UTC
Ver. 2.0.9

There seems to be a conflict with Laravel Nova 4.10.1. When adding the HasTabs trait to a resource, relationship panels are hidden on the update/create screens.

<img width="1070" alt="Screenshot 2022-06-28 at 13 53 33" src="https://user-images.githubusercontent.com/5261690/176172731-6f677865-ae05-4fbc-ac18-4e7484b30194.png">

<img width="783" alt="Screenshot 2022-06-28 at 13 53 23" src="https://user-images.githubusercontent.com/5261690/176172745-79342c2d-abb7-4d78-84c9-78ad0c946bf8.png">

----

When removing the trait:

<img width="1296" alt="Screenshot 2022-06-28 at 13 59 26" src="https://user-images.githubusercontent.com/5261690/176173293-038f6fb2-d69d-4bed-9b9f-d15d3c7f8ee5.png">

**Comment by marcfilipan** [comment] 2022-06-28 12:20
Seems to work fine for me:
<img width="2712" alt="image" src="https://user-images.githubusercontent.com/1815234/176176976-03e9865a-d323-4f56-a23e-b9f19129e1bf.png">

**Comment by marcfilipan** [comment] 2022-06-28 12:21
Actually i see now i miss a bunch of tabs, never mind.

**Comment by marcfilipan** [comment] 2022-06-28 12:59
Try 2.1.0

<img width="2677" alt="image" src="https://user-images.githubusercontent.com/1815234/176184540-395e4f20-a308-440f-973d-1ed117b46026.png">

**Comment by marcfilipan** [comment] 2022-06-28 13:29
With 4.10.1 I seem to have everything back.

Keep in mind, HasMany and MorphMany, shouldn't show up on create/update, that's simply per Nova's design.

<img width="2702" alt="image" src="https://user-images.githubusercontent.com/1815234/176190814-730c885d-a10e-41d7-9b03-eab05601c5bd.png">

**Comment by mikkellindblom** [comment] 2022-07-06 11:47
It seems to be broken again in 4.11.1 @marcfilipan

**Comment by jorgeneira** [comment] 2022-07-19 01:37
on nova 4.12.6 the HasTabs trait actually makes all HasMany relationships dissapear in details view, also with erros in console:

TypeError: Cannot read properties of undefined (reading '0')

**Comment by chrisbjr** [comment] 2022-07-20 03:21
Looks like it only works now for Nova v4.10.1. We downgraded to make it work for the meantime because it's broken in Nova v4.12.x.

Thanks

**Comment by marcfilipan** [comment] 2022-07-20 06:40
I'll be able to take a look at it at the of the week.

**Comment by mstaack** [comment] 2022-08-14 21:01
@marcfilipan anything i can do to help fixing this issue?

**Comment by mstaack** [comment] 2022-08-16 10:23
@crynobone said this is related to the change in 4.12 `Nova will now retain the user-defined panel sort order.`
![image](https://user-images.githubusercontent.com/10169509/184857320-11246d01-e959-441c-9a1a-9d89ae7163fb.png)

**Comment by albalooshi** [comment] 2022-08-28 16:26
@mstaack were you able to solve the issue?

**Comment by s-fog** [comment] 2022-08-30 12:43
We are really waiting for you. Thanks!

**Comment by marcfilipan** [comment] 2022-08-31 02:05
I have everything updated to latest, and it seems to work fine for me.

I'll try it on a fresh install to see if something goes wrong.

**Comment by jakelehner** [comment] 2022-08-31 15:41
I can confirm I'm experiencing the issue on anything above Nova 4.11. Running Laravel 8, PHP 7.4, Nova Tabs 2.1.

When I upgrade Nova to 4.12 or the latest (4.17 I believe), relationship panels no longer display if they aren't wrapped in a tab if the `HasTabs` trait is present.

**Comment by ianrobertsFF** [comment] 2022-09-07 16:49
I guess the solution is wrap relationships in a Tab?

I've always had mine wrapped in a Tab and I've not seen this issue once, so it might be worth just updating docs to make that the recommended way of displaying them?

**Comment by mstaack** [comment] 2022-09-08 08:11
@marcfilipan the issues happens when the relations are not within a tab.
try reproducing this as soon as you can ;)

**Comment by crynobone** [comment] 2022-09-08 09:39
Can anyone tests this fix: https://github.com/eminiarts/nova-tabs/pull/247

**Comment by marcfilipan** [comment] 2022-09-08 10:30
Fixed in https://github.com/eminiarts/nova-tabs/releases/tag/2.2.0

**Closed by marcfilipan** 2022-09-08 10:30 UTC
Labels: bug
