### ISSUE TITLE
Cannot install this package in my composer

### ISSUE THREAD

**Issue by ardasatata** [eminiarts/nova-tabs#52] opened 2019-09-11 09:46 UTC
Hello Im using nova v 2.1.0 but when im tried to install this package using composer it goes like this

```
Using version ^1.1 for eminiarts/nova-tabs
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for eminiarts/nova-tabs ^1.1 -> satisfiable by eminiarts/nova-tabs[1.1.0].
    - eminiarts/nova-tabs 1.1.0 requires laravel/nova ^2.1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by vbezruchkin** [comment] 2019-11-21 18:37
Hi,

The problem is typical for the case when you don't use repository URL for your nova package and add it as folder to your application.

```
    "repositories": {
        "eminiarts/nova-tabs": {
            "type": "path",
            "url": "./custom/nova-tabs"
        },
        "laravel/nova": {
            "type": "path",
            "url": "./nova"
        },
    },
```
You can create folder `custom` and put the latest version of nova-tabs package there. Once done, please make sure you updated your `composer.json to` symlink your composer to proper package folder. 
Then delete `composer.lock` & `vendor` folder and run `composer install`

Also make sure your composer.json require section contains * for the package:
```
    "require": {
...
        "eminiarts/nova-tabs": "*",
...
    }
```

Hope this helps.

**Comment by RVxLab** [comment] 2020-10-19 10:16
Due to the age of this issue and my attempt to clean everything up I'm closing this. If this is still a problem for you, please re-open this or create a new one.

**Closed by RVxLab** 2020-10-19 10:16 UTC
