### ISSUE TITLE
HasMany & morphMany break when I use fieldForIndex & fieldForDetail

### ISSUE THREAD

**Issue by ziming** [eminiarts/nova-tabs#177] opened 2022-03-07 16:23 UTC
they still show on the detail page but when i click the create XYZ button, the new page is blank

my current setup is fieldsForIndex() for the index fields

fieldsForDetail() for the detail view with tabs

and fields() for the create/edit layout with tabs.

**Comment by RVxLab** [comment] 2022-03-07 22:00
Can you create a private repo with a minimal example and invite me to it?

**Comment by ziming** [comment] 2022-03-09 19:51
Hi turn out I just have to repeat those HasMany in fields(), fieldsForUpdate(), fieldsForCreate()

Having HasMany in fieldsForDetail() is not enough to get it working

So it's fine now unless you consider it a bug

**Comment by RVxLab** [comment] 2022-03-10 03:43
Ah okay. This sounds like Nova thing and not so much a nova-tabs things. I'm pretty sure that `fields` is for all of them and `fieldsForThing` is for the individual actions.

I'll close this issue as this is not a bug.

**Closed by RVxLab** 2022-03-10 03:43 UTC
