### ISSUE TITLE
tab's name is not support Chinese?

### ISSUE THREAD

**Issue by niunaiyi** [eminiarts/nova-tabs#232] opened 2022-07-10 03:45 UTC
new Tabs('投放点详情', [
                '详情'    => [
                    Text::make('名称', 'name')
                        ->sortable()
                        ->rules('required', 'max:20'),
                ],
                '视频' => [
                    HasMany::make('视频','videos',Video::class)
                ],
            ]),

then layout is wrong.

**Comment by marcfilipan** [comment] 2022-07-10 10:13
You can always submit a PR that would fix it. 

I don't use or know Chinese, so can't help you.

**Comment by RVxLab** [comment] 2022-08-14 22:54
This is more or less a duplicate of #145 and #167

It has to do with `Str::slug` stripping out what I assume to be non-Latin characters.

**Closed** 2022-09-08 10:33 UTC
